[MISC] Reusable workflow (#168)
* Reusable workflow

* Add groups

* Single unit test suite

* Bump dpw version

* Downgrade pytest-asyncio

* Properly resolve pytest-asyncio

* Charmcraft override

* Unpin duplicate test dependencies

* Wrong release branch

* Bump Juju agents

* Remove discourse test

* Downgrade data_intefaces

* Wrong var

* Revert back to juju 3.1.6

* Update .gitignore

Co-authored-by: Carl Csaposs <carl.csaposs@canonical.com>

* Switch to strict dependencies

* Fix lib-check

* Binary psycopg3

* Try with only bin packages being listed in charmcraft.yam

* Disable regex manager

* Switch to pack-wrapper

* Move requirements

* Try without redundant dependency

---------

Co-authored-by: Carl Csaposs <carl.csaposs@canonical.com>

diff --git a/charmcraft.yaml b/charmcraft.yaml
--- a/charmcraft.yaml
+++ b/charmcraft.yaml
@@ -12,6 +12,14 @@ bases:
 
 parts:
   charm:
+    override-pull: |
+      craftctl default
+      if [[ ! -f requirements.txt ]]
+      then
+          echo 'ERROR: Use "tox run -e build" instead of calling "charmcraft pack" directly' >&2
+          exit 1
+      fi
+    charm-strict-dependencies: true
     build-packages:
       - libffi-dev
       - libssl-dev
@@ -19,5 +27,5 @@ parts:
       - cargo
       - pkg-config
     charm-binary-python-packages:
-      - psycopg2-binary==2.9.9  # renovate
-      - psycopg[binary]==3.1.12  # renovate
+      - psycopg2-binary
+      - psycopg-binary
